# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

domain: razvr.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://razvr.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /my.site/      # place folder name if the site is served in a subfolder

# Localhost Jekyll Server Settings
#host: '0.0.0.0'
#port: '4000'
#root: /my.site

# Basic Blog Details
title: 'Razur site'
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "_site" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: '/:year/:month/:title/'

markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _scss
  style: :compressed

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
email: RachelAZurawski@gmail.com
twitter_username: _Razur
github_username:  razvr
